# Generated by Django 4.2.13 on 2024-09-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropdown',
            name='field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dropdown',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
