# Generated by Django 4.2.13 on 2024-10-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_dropdown_field_alter_dropdown_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropdown',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
