# Generated by Django 4.2.13 on 2024-06-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_fav_color_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pic/default_profile_pic.png', upload_to='profile_pic'),
        ),
    ]
