# Generated by Django 5.0.6 on 2024-06-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_plan_object_id_tasks_object_id_tasks_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
