# Generated by Django 4.2.13 on 2024-10-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessments',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
    ]
