# Generated by Django 4.2.13 on 2024-09-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessments',
            name='ai_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='ai_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
