# Generated by Django 4.2.13 on 2024-10-15 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_question_learn_content_learn'),
    ]

    operations = [
        migrations.AddField(
            model_name='learn',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_course', to='learn.courses'),
        ),
        migrations.AlterField(
            model_name='question',
            name='learn_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_learn_content', to='learn.learn'),
        ),
    ]
